dependencies:
  # https://github.com/helm/charts/tree/master/stable/nginx-ingress
  - name: nginx-ingress
    version: "0.31.0"
    repository: "https://kubernetes-charts.storage.googleapis.com"

  # https://github.com/helm/charts/tree/master/stable/cert-manager
  - name: cert-manager
    version: "v0.5.2"
    repository: "https://kubernetes-charts.storage.googleapis.com"

  # https://github.com/jupyterhub/binderhub
  # https://jupyterhub.github.io/helm-chart/
  - name: binderhub
    version: "0.2.0-5be4d08"
    repository: "https://jupyterhub.github.io/helm-chart"
