# Values for the parent chart, passed to subcharts

letsencrypt:
  contactEmail: erik.i.sundell@gmail.com

# Default values: https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/values.yaml
binderhub:
  config:
    BinderHub:
      hub_url: 'https://hub.neurips.mybinder.org'
      use_registry: true
      image_prefix: gcr.io/binder-prod/neurips-

  service:
    type: ClusterIP

  ingress:
    enabled: true
    annotations:
      # cert-manager provides a TLS secret
      kubernetes.io/tls-acme: "true"
      # nginx-ingress controller to be explicitly utilized instead of "gce"
      kubernetes.io/ingress.class: nginx
    hosts:
      - neurips.mybinder.org
    tls:
      - secretName: neurips-mybinder-org-tls
        hosts:
          - neurips.mybinder.org

  # Default values: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml
  jupyterhub:
    hub:
      extraConfig:
        gpus-for-all: |
          c.KubeSpawner.extra_resource_guarantees = {"nvidia.com/gpu": "1"}
          c.KubeSpawner.extra_resource_limits = {"nvidia.com/gpu": "1"}
    proxy:
      service:
        type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/proxy-body-size: 64m
      hosts:
        - hub.neurips.mybinder.org
      tls:
        - secretName: hub-neurips-mybinder-org-tls
          hosts:
            - hub.neurips.mybinder.org
    scheduling:
      podPriority:
        enabled: true
      userScheduler:
        enabled: true
      userPlaceholder:
        enabled: true
        replicas: 0
      userPods:
        nodeAffinity:
          matchNodePurpose: require
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    singleuser:
      memory:
        limit: 7G
        guarantee: 1G
      cpu:
        limit: 2
        guarantee: 0.05

# Default values: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml
nginx-ingress:
  controller:
    service:
      # I reserved an regional ip address in us-east1...
      # > gcloud compute addresses create neurips-mybinder-org --region us-east1
      # ... and inspected what address got ...
      # > gcloud compute addresses list
      # ... and assigned the IP to the field below
      loadBalancerIP: 35.190.132.172
  config:
    # Allow POSTs of upto 64MB, for large notebook support.
    proxy-body-size: 64m

# Default values: https://github.com/helm/charts/blob/master/stable/cert-manager/values.yaml
cert-manager:
  ingressShim:
    defaultIssuerName: "neurips"
    defaultIssuerKind: "ClusterIssuer"
    defaultACMEChallengeType: "http01"
