# Values for the parent chart, passed to subcharts

letsencrypt:
  contactEmail: erik.i.sundell@gmail.com

# Default values: https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/values.yaml
# MyBinder.org values: https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml
binderhub:
  config:
    BinderHub:
      hub_url: 'https://hub.neurips.mybinder.org'
      use_registry: true
      image_prefix: gcr.io/binder-prod/neurips-
      about_message: |
        <p>mybinder.org is public infrastructure operated by the <a href="https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html#binder-team">Binder Project team</a>.<br /><br />
        This is a temporary deployment for NeurIPS 2019 and will stop existing after the conference is over.<br /><br />
        The Binder Project is a member of <a href="https://jupyter.org">Project Jupyter</a>, which is a fiscally
        sponsored project of <a href="https://numfocus.org/">NumFocus</a>, a US 501c3 non-profit.<br /><br />
        For abuse please email: <a href="mailto:binder-team@googlegroups.com">binder-team@googlegroups.com</a>, to report a
        security vulnerability please see: <a href="https://mybinder.readthedocs.io/en/latest/faq.html#where-can-i-report-a-security-issue">Where can I report a security issue</a><br /><br />
        For more information about the Binder Project, see <a href="https://docs.mybinder.org/about">the About Binder page</a></p>

  service:
    type: ClusterIP

  ingress:
    enabled: true
    annotations:
      # cert-manager provides a TLS secret
      kubernetes.io/tls-acme: "true"
      # nginx-ingress controller to be explicitly utilized instead of "gce"
      kubernetes.io/ingress.class: nginx
    hosts:
      - neurips.mybinder.org
    tls:
      - secretName: neurips-mybinder-org-tls
        hosts:
          - neurips.mybinder.org

  networkPolicy:
    enabled: false
    egress:
      tcpPorts:
        - 80 # http
        - 443 # https
        - 9418 # git
        - 873 # rsync
        - 1094 # xroot
      cidr: 0.0.0.0/0

  # Default values: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml
  jupyterhub:
    cull:
      # cull every 11 minutes so it is out of phase
      # with the proxy check-routes interval of five minutes
      every: 660
      timeout: 600
      # maxAge is 2 hours: 2 * 3600 = 7200
      maxAge: 7200
    prePuller:
      continuous:
        # WARNING: The following toleration was manually added with
        # kubectl edit ds continuous-image-puller
        #
        #   tolerations:
        #   - effect: NoSchedule
        #     key: nvidia.com/gpu
        #     operator: Exists
        enabled: true
      # using this as singleuser's image instead as that will always be pulled
      extraImages:
        # an init-container that we use
        # It's only 3MB, ah well...
        # see: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1046
        init-image:
          name: minrk/tc-init
          tag: 0.0.4
        demo1:
          name: gcr.io/binder-prod/neurips-jzf2101-2dshap-8561f0
          tag: 4572eb360937c90a3fe92649f89ec030ca293205
        #demo2:
        #  name: gcr.io/binder-prod/neurips-jzf2101-2dtutorial-66ab00
        #  tag: d8f23c902ae59b0a59515aa8c27cc65a5cd7956d
        demo3:
          name: gcr.io/binder-prod/neurips-jzf2101-2dgan-5ftutorial-54d291
          tag: a8f7b8e357e8bbd4b7bdad7a23b9691689c18c3c
        demo4:
          name: gcr.io/binder-prod/neurips-jzf2101-2dmxnet-2dthe-2dstraight-2ddope-b7541c
          tag: 338f3365b17487e50e090ec24bd58d0b9c32d721

    hub:
      extraConfig:
        neverRestart: |
          c.KubeSpawner.extra_pod_config.update({'restart_policy': 'Never'})
      activeServerLimit: 100
      networkPolicy:
        enabled: false
    proxy:
      service:
        type: ClusterIP
      networkPolicy:
        enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
      hosts:
        - hub.neurips.mybinder.org
      tls:
        - secretName: hub-neurips-mybinder-org-tls
          hosts:
            - hub.neurips.mybinder.org
    scheduling:
      podPriority:
        enabled: true
      userScheduler:
        enabled: true
      userPlaceholder:
        enabled: true
        replicas: 16
      userPods:
        nodeAffinity:
          matchNodePurpose: prefer
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    singleuser:
      # to allow a scaleup event to finish in worst case scenario
      # which will be required without placeholders
      startTimeout: 1200
      initContainers:
        - name: tc-init
          image: minrk/tc-init:0.0.4
          env:
            - name: WHITELIST_CIDR
              value: 10.0.0.0/8
            - name: EGRESS_BANDWIDTH
              value: 1mbit
          securityContext:
            # capabilities.add seems to be disabled
            # by the `runAsUser: 1000` in the pod-level securityContext
            # unless we explicitly run as root
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN
      networkPolicy:
        enabled: false
        egress: []
      storage:
        # allows us to configure jupyter notebook
        extraVolumes:
          - name: etc-jupyter
            configMap:
              name: user-etc-jupyter
          - name: etc-jupyter-templates
            configMap:
              name: user-etc-jupyter-templates
        extraVolumeMounts:
          - name: etc-jupyter
            mountPath: /etc/jupyter
          - name: etc-jupyter-templates
            mountPath: /etc/jupyter/templates

      image:
        # this image is not supposed to be started, but it's
        # nice to get it pulled ahead of time to reduce pull
        # time of other images depending on it
        name: buildpack-deps
        tag: bionic
      memory:
        limit: 20G
        guarantee: 4G
      cpu:
        limit: 8
        guarantee: 0.9
      extraResource:
        limits:
          "nvidia.com/gpu": 1
        guarantees:
          "nvidia.com/gpu": 1

# these config files will be mounted on the user pods storage
etcJupyter:
  jupyter_notebook_config.json:
    NotebookApp:
      # shutdown the server after no activity
      shutdown_no_activity_timeout: 600

    # if a user leaves a notebook with a running kernel,
    # the effective idle timeout will typically be CULL_TIMEOUT + CULL_KERNEL_TIMEOUT
    # as culling the kernel will register activity,
    # resetting the no_activity timer for the server as a whole
    MappingKernelManager:
      # shutdown kernels after no activity
      cull_idle_timeout: 600
      # check for idle kernels this often
      cull_interval: 60
      # a kernel with open connections but no activity still counts as idle
      # this is what allows us to shutdown servers
      # when people leave a notebook open and wander off
      cull_connected: true

# Default values: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml
nginx-ingress:
  controller:
    service:
      # I reserved an regional ip address in us-east1...
      # > gcloud compute addresses create neurips-mybinder-org --region us-east1
      # ... and inspected what address got ...
      # > gcloud compute addresses list
      # ... and assigned the IP to the field below
      loadBalancerIP: 35.190.132.172
    config:
      # Allow POSTs of upto 64MB, for large notebook support.
      proxy-body-size: 64m

# Default values: https://github.com/helm/charts/blob/master/stable/cert-manager/values.yaml
cert-manager:
  ingressShim:
    defaultIssuerName: "neurips"
    defaultIssuerKind: "ClusterIssuer"
    defaultACMEChallengeType: "http01"
